name: Run eslint with reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: eslint
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          github_token:
            ${{ secrets.github_token }}
            # Change reporter.
